name: Content API CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Build with Gradle
        run: ./gradlew build -xtest
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Publish jar to GitHub package
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Push image to GitHub Packages
#        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: zran-nz/content-api/content-api
#          tag_with_ref: true

